### ISSUE TITLE
Frame Publisher icon

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#10]
Maybe similar to the Pupil Remote icon but having the "wave symbol" in the top right instead of the bottom left. This way it looks like something is sent away instead of being received.

**Comment by nathakits** [comment]
@papr @willpatera - how about this instead? A video frame icon with the signal broadcasting.

![frame_publisher](https://user-images.githubusercontent.com/17331040/31272632-da29ee5a-aab5-11e7-8066-3f2f5f11acf8.PNG)
