### ISSUE TITLE
Time Sync icon

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#12]
Maybe similar to a clock but having to arrows around the clock hands instead of having a full circle.

**Comment by nathakits** [comment]
@papr - https://material.io/icons/#ic_update or https://material.io/icons/#ic_slow_motion_video or https://material.io/icons/#ic_rotate_right

**Comment by papr** [comment]
Is it possible to edit the first one two have a second arrow in the bottom left to emphasize the syncing aspect?

The second one  is a nice idea but does not work as well as the first one for me. The third one misses the time aspect.

**Comment by willpatera** [comment]
Ok - let's do double arrow here as @papr suggests. A variation of ic_update.

**Comment by nathakits** [comment]
@papr @willpatera  Time sync icon

![time_sync](https://user-images.githubusercontent.com/17331040/31271394-914a212c-aab1-11e7-9db2-a1b28f287c8c.PNG)

**Comment by papr** [comment]
Perfect!
