### ISSUE TITLE
Revision of the "source" icon

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#14]
We are currently using the source icon (`s`, `0xec01`) as the icon for the source manager (different from the plugin manager) and the active source (`as`, `0xe412`) icon for the active source plugin itself.

It was not clear for multiple people in the office what the source `s` icon was supposed to visualize nor what it represented. It would be great if the icon could be revised such that it would be clearer what the represented plugin is.

The source manager has three main functionalities:
1. Choose the input source _type_
2. List all available sources for the given type
3. Activate a selected source

**Comment by willpatera** [comment]
It is challenging to create the "perfect" icon for this plugin. 

Here are some ideas:
- https://material.io/icons/#ic_playlist_add (list and action) 
- https://material.io/icons/#ic_playlist_play (something that communicates a list and action)
- https://material.io/icons/#ic_airplay
- I know that sources are not just USB sources - but the USB icon could be of use here: https://material.io/icons/#ic_usb

**Comment by nathakits** [comment]
The initial idea of the `s` icon is to show the camera outline with the input as the source (plug). And when a source is active, then the input becomes active (circle) while the camera outline is still the same. To show that these two icons are related to each other. That was what i intended for the icons to be.

It is challenging to create this icon indeed. Maybe modifying the usb icon could also work.

**Comment by nathakits** [comment]
@willpatera @papr - how about this? An icon showing lists and USB-like sources

![sources](https://user-images.githubusercontent.com/17331040/31224925-0739ed12-a9fa-11e7-932e-b0a120ad32d3.PNG)

**Comment by papr** [comment]
I think the right one would be a great icon for the source manager.

**Comment by willpatera** [comment]
OK - lets go with the one on the right 👍

**Comment by mkassner** [comment]
done
