### ISSUE TITLE
Player control icons

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#15]
Missing icons:
- play
- seek forwards
- seek backwards
- export

See current version for possible icons.

**Comment by nathakits** [comment]
@papr - possible icons
play - https://material.io/icons/#ic_play_arrow
seek forwards - https://material.io/icons/#ic_fast_forward
seek backwards - https://material.io/icons/#ic_fast_rewind
export - https://material.io/icons/#ic_arrow_downward or https://material.io/icons/#ic_vertical_align_bottom or https://material.io/icons/#ic_file_download

**Comment by papr** [comment]
They all look great, I think I like https://material.io/icons/#ic_file_download most for export.

**Comment by willpatera** [comment]
For export it should be https://material.io/icons/#ic_vertical_align_bottom or https://material.io/icons/#ic_file_download - the file download icon is very thick/heavy but relative to other icons, it should be ok.

**Comment by nathakits** [comment]
I think i will go with the - > https://material.io/icons/#ic_file_download - since its relative to the other icons. Otherwise i could adjust the thickness of the arrow.
