### ISSUE TITLE
Accuracy / Vis_Cross icon distinction

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#16]
I am currently using the `vcr`/`0xe1b7` icon for the accuracy test. I know that it was supposed to be used for the `Vis_Cross` plugin but I have the feeling that a new icon for the `Vis_Cross` icon would be appropriate. I am thinking about an icon that is closer to the plugin's visualization: Crosshair, similar to the current icon but longer, no circle.

**Comment by willpatera** [comment]
@nathakits any thoughts on this.

**Comment by nathakits** [comment]
I think both the `accuracy test` icon and `vis_cross` icon can both be improved. As @papr said the `vis_cross` crosshar could be longer and maybe with a little circle in the middle. For the `accuracy test` icon . I am thinking something like showing the crosshair with the reference points and matching gaze positions.

**Comment by nathakits** [comment]
@papr - could i bother you with a screenshot of `accuracy vis` in action? so i could use it for designing the new icon.

**Comment by nathakits** [comment]
@papr @willpatera - what do you guys think of just using the `share` icon for the `accuracy vis`? -
 https://material.io/icons/#ic_share

**Comment by willpatera** [comment]
@nathakits this kind of works - but maybe should be more related to calibration icon.

**Comment by nathakits** [comment]
@willpatera calibration icon as in the `C` button?

**Comment by willpatera** [comment]
@nathakits - I thought that we had an icon for calibration. Anything in here: https://pupil-labs.github.io/pupil-icon-font/ ?

**Comment by nathakits** [comment]
@willpatera - there is a `offline calibration` icon. Did you mean this one?
![calibration](https://user-images.githubusercontent.com/17331040/31250560-51d035f2-aa45-11e7-8d8e-21581c4206d3.PNG)

**Comment by papr** [comment]
We are using it for both, capture and player calibration. But maybe it should be more like the calibration marker...

**Comment by nathakits** [comment]
@papr - You mean the `offline calibration` icon should be more like the calibration marker correct? In that case i could open a new issue and work on that as well.

**Comment by papr** [comment]
The icon is #20 is exactly what I meant. The accuracy test calculates the angular difference between a desired point and an actual point. Maybe we can work with that?

**Comment by nathakits** [comment]
@papr @willpatera - how about this? The icon shows a matched gaze position (the calibration marker) with a reference point.

![vis_accuracy](https://user-images.githubusercontent.com/17331040/31268554-1705f896-aaa7-11e7-9383-ebe82ec0f6a2.PNG)

**Comment by papr** [comment]
I think it is great!
