### ISSUE TITLE
Missing icon for System_Graphs plugin

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#18]
We decided to move the system graphs (cpu, fps, confidences) into a separate plugin which will require its own icon. I thought about something like this: http://fontello.com/#search=bar

**Comment by nathakits** [comment]
@papr what about something like this? - https://material.io/icons/#ic_equalizer

**Comment by papr** [comment]
Looks good!

**Comment by willpatera** [comment]
This icon looks good let's add it.
