### ISSUE TITLE
Overview with icons and glyphs 

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-icon-font#2]
@nathakits please upload a .pdf with the icon font and mappings to this repo. Alternative is to put it on fontello and share a permalink if that is possible.

**Comment by papr** [comment]
It would be great if this could be part of the build process or in case of the link an hook that publishes the current build similar to pupil docs.

**Comment by nathakits** [comment]
@willpatera - added icon font pdf

PR https://github.com/pupil-labs/pupil-icon-font/pull/3

**Comment by willpatera** [comment]
I will merge #3 so that there is an immediate reference. However, I have discussed with @nathakits making a simple `index.html` file that will be built from the `config.yml` file. This way there will always be a reference for glyphs and their unicodes. 

I will leave this issue open, and will close after @nathakits has made the above mentioned file.

**Comment by papr** [comment]
Thank you! The html file is a great idea. :+1:

**Comment by nathakits** [comment]
@willpatera - icon font html PR - https://github.com/pupil-labs/pupil-icon-font/pull/4

**Comment by willpatera** [comment]
closed with #4
