### ISSUE TITLE
Camera Intrinsics Estimation plugin

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#25]
The Camera Intrinsics Estimation plugin has been converted to a stand-alone plugin in pupil-labs/pupil#883. Therefore, it requires its own icon. I thought that an abstract version of the usual camera model visualization would do:
![](https://gbai.files.wordpress.com/2009/12/frustum1.png)

**Comment by nathakits** [comment]
@papr - as discussed with @willpatera, we decided to go with this icon for the Camera Intrinsics Estimation plugin.
![cie](https://user-images.githubusercontent.com/17331040/34512564-ebc01876-f095-11e7-8931-797577abf3ad.png)

This icon will be in the this PR - https://github.com/pupil-labs/pupil-icon-font/pull/28

**Comment by willpatera** [comment]
merged; closing 😄
