### ISSUE TITLE
Hololens Relay plugin icon

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#26]
We are developing an udp version of Pupil Remote for the Hololens integration. It would be nice to have an icon for it as well. We can probably re-use the Remote icon and modify it slightly -- maybe by adding 'udp' test to it.

**Comment by papr** [comment]
Actually, we are going to rename it to `Hololens Relay`. Therefore it would be great to have an abstract hololens in the icon.

**Comment by papr** [comment]
I have something like these in mind:

![image](https://user-images.githubusercontent.com/168390/33603935-8c6b2e9e-d9b4-11e7-9958-8f48041ea3b5.png)
[Source](https://www.onlinewebfonts.com/icon/476264)

![](https://compass-ssl.microsoft.com/assets/d5/75/d5759537-5d8c-4e8f-a800-60017263b77b.svg?n=hololens_logo.svg)
[Source](https://compass-ssl.microsoft.com/assets/d5/75/d5759537-5d8c-4e8f-a800-60017263b77b.svg?n=hololens_logo.svg)

**Comment by nathakits** [comment]
@papr - as discussed with @willpatera, we decided to go with this icon for the Hololens Relay plugin.
![hlr](https://user-images.githubusercontent.com/17331040/34512410-f10160a2-f094-11e7-80b2-483c631caed4.png)

  This icon will be in the this PR - https://github.com/pupil-labs/pupil-icon-font/pull/28

**Comment by willpatera** [comment]
merged; closing 😄
