### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-icon-font#27]
Icons to update
- vis lightpoints
- vis polyline
- source
- vis fixation
- vis cross
- pupil detector 2d
- pupil detector 3d
- gaze mapper

icons to remove
- 2d and 3d fixation

**Comment by nathakits** [comment]
Update icon font with this PR - https://github.com/pupil-labs/pupil-icon-font/pull/28

**Comment by willpatera** [comment]
Merged; closing 😄
