### ISSUE TITLE
Pause icon

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#29]
I would like to improve the user feedback for the Player play button by giving it two states:
1. Show `Play` icon while playback is paused
2. Show `Pause` icon during playback

**Comment by willpatera** [comment]
@nathakits please add Pause icon `||`

**Comment by nathakits** [comment]
@willpatera icon PR - https://github.com/pupil-labs/pupil-icon-font/pull/32

**Comment by willpatera** [comment]
Merged with #32 closing :smile:
