### ISSUE TITLE
Skip/seek previous icon 

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#30]
In order to implement https://github.com/pupil-labs/pupil/issues/1013 ~and Reverse Playback~ I would like to propose the following three button user interface:

1. During playback: `fast rewind` / `pause` / `fast forward`
2. During paused playback: `skip prev` / `play` / `skip next`

- `fast forward` would increase playback speed \*
- `fast rewind` would decrease playback speed \*
- `skip prev` would seek to the previous frame
- `skip next` would seek to the next frame

This would allow us to have two different interaction modes for player:
1. playback mode
2. frame-by-frame mode

\* Maybe there is a better icon than `fast rewind`for symbolizing playback slow down...

**Comment by willpatera** [comment]
~~@papr there are icons out there in the wild/in libraries already. The below ascii version are common for interfaces already.~~ Edit: All already exist in our library except for Pause, which is issue #29 - this issue will be closed. 

Play = `>`
FF = `>>`
Rewind = `<<`
Pause = `||`
Skip previous = `|<`
Skip next = `>|`

Edit - @papr these icons are already available. Please see: https://pupil-labs.github.io/pupil-icon-font/
