### ISSUE TITLE
Icons for pupil detector settings within the eye windows icon bar

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#5]
Currently I am using the `roboto` strings `2D` and `3D` See screenshot below. It would be great to have an dedicated icons for that. Two implementation ideas:

1. just use `2D` and `3D` and scale it accordingly to icon size
2. Reuse the `opd` icon and add `2D` and `3D` to the top right similar to `3dfd` (which we will not need anymore as soon as I have time to refactor the offline fixation detectors)

![image](https://user-images.githubusercontent.com/168390/30100461-473cf76a-92e9-11e7-81e6-af6c8f51b7fe.png)

**Comment by nathakits** [comment]
@papr - how about this?

![pd](https://user-images.githubusercontent.com/17331040/31111274-fb4ffc9a-a836-11e7-858f-1fc92aa9023c.PNG)

**Comment by willpatera** [comment]
@nathakits this is OK for me.

**Comment by papr** [comment]
We would have to test visibility of the dot but that is what I had in mind :)

**Comment by papr** [comment]
The `2d`/`3d` text needs an increase in size in the next revision.
