### ISSUE TITLE
Gaze mapper icons

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-icon-font#6]
* Missing icon
* Maybe somethign abstract like this: http://fontello.com/#search=map
* Alternatively an arrow indicating a mapping in the mathematical sense

**Comment by nathakits** [comment]
@papr @willpatera - how about this?

![gaze_mapper](https://user-images.githubusercontent.com/17331040/31273297-309bb9d8-aab8-11e7-9997-57453cdf5a12.PNG)

**Comment by papr** [comment]
If this is the gaze mapper, what is `U+EC03`?

edit: I just realized that this is the icon for `vis_fixation`. Maybe we should make it consistent with the fixation detector plugin.

**Comment by nathakits** [comment]
@papr - can you elaborate on this?

**Comment by papr** [comment]
`vis fixation` looks similar to `offline calibration` within a frame. It was just not clear to me which icon to use for what plugin. But this has been resolved by adding the full name feature to the icon overview.
